---

- name: validate {{ juniper_build }} access
  ansible.builtin.file:
    path: "{{ juniper_build }}"
    state: directory
  run_once: true

- name: generage default community config
  template:
    src: default-community.conf.j2
    dest: "{{ juniper_build }}/default-community.conf"

- name: upload default community config
  junipernetworks.junos.junos_config:
    src: "{{ juniper_build }}/default-community.conf"
    update: replace
    comment: update config
    src_format: text
    check_commit: "{{ check | default('yes') }}"
    confirm: "{{ confirm | default(0) }}"
    comment: ansible configured

- name: generage default policy-options config
  template:
    src: default-policy-options.conf.j2
    dest: "{{ juniper_build }}/default-policy-options.conf"

- name: upload default policy-options config
  junipernetworks.junos.junos_config:
    src: "{{ juniper_build }}/default-policy-options.conf"
    update: replace
    comment: update config
    src_format: text
    check_commit: "{{ check | default('yes') }}"
    confirm: "{{ confirm | default(0) }}"
    comment: ansible configured

- name: generage local preferences config
  template:
    src: lp-policy-options.conf.j2
    dest: "{{ juniper_build }}/lp-policy-options.conf"

- name: upload local preferences config
  junipernetworks.junos.junos_config:
    src: "{{ juniper_build }}/lp-policy-options.conf"
    update: replace
    comment: update config
    src_format: text
    check_commit: "{{ check | default('yes') }}"
    confirm: "{{ confirm | default(0) }}"
    comment: ansible configured

- name: generate managed uplink bgp config
  template:
    src: bgp.uplink.conf.j2
    dest: "{{ juniper_build }}/{{ item.name }}-bgp.uplink.conf"
  with_items: "{{ bgp_uplinks }}"
  when: bgp_uplinks is defined

- name: upload managed community config
  junipernetworks.junos.junos_config:
    src: "{{ juniper_build }}/{{ item.name }}-bgp.uplink.conf"
    update: replace
    comment: update config
    src_format: text
    check_commit: "{{ check | default('yes') }}"
    confirm: "{{ confirm | default(0) }}"
    comment: ansible configured
  with_items: "{{ bgp_uplinks }}"
  when: bgp_uplinks is defined
